version: '3.2'


services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    stdin_open: true
    tty: true
    networks:
       redeteste:
        ipv4_address: 10.5.0.10
        
  
  debian:
    image: debian:latest
    container_name: debian
    stdin_open: true
    tty: true
    networks:
      redeteste:
        ipv4_address: 10.5.0.11


  rockylinux: 
    image: rockylinux:9
    container_name: rockylinux
    stdin_open: true
    tty: true
    networks:
       redeteste:
        ipv4_address: 10.5.0.12

  alpine:
    image: alpine
    container_name: alpine
    stdin_open: true
    tty: true
    networks:
      redeteste:
        ipv4_address: 10.5.0.13


networks:
  redeteste:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

