version: '3.2'


services:
  ubuntu:
    image: ubuntu:20.04
    container_name: ubuntu
    stdin_open: true
    tty: true
    networks:
       redeteste:
        ipv4_address: 10.5.0.10
        
  
  debian:
    image: debian
    container_name: debian
    stdin_open: true
    tty: true
    networks:
      redeteste:
        ipv4_address: 10.5.0.11


  centos:
    image: centos
    container_name: centos
    stdin_open: true
    tty: true
    networks:
       redeteste:
        ipv4_address: 10.5.0.12

  alpine:
    image: alpine
    container_name: alpine
    stdin_open: true
    tty: true
    networks:
      redeteste:
        ipv4_address: 10.5.0.13


networks:
  redeteste:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

