version: '3.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      redetestenginx:
        ipv4_address: 10.6.0.2


# por padrão, o nginx olha o diretório /usr/share/ngix/html
# diretório de config: /etc/nginx/nginx.conf
# arquivo de config da web do nginx: /etc/nginx/conf.d/default.conf

  node1:
    image: nginx:latest
    container_name: node1
    ports:
      - "80"
    networks:
      redetestenginx:
        ipv4_address: 10.6.0.3
#################################################
# Para load balancer add 1 ou mais nodes:

  node2:
     image: nginx:latest
     container_name: node2
     ports:
      - "80"
     networks:
      redetestenginx:
        ipv4_address: 10.6.0.4
###############################################
networks:
  redetestenginx:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.0.0/16
         gateway: 10.6.0.1
