version: '3.2'

services:     
  sqlserver2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2019
    environment:
      - SA_PASSWORD=01233210
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=True
    ports:
      - "1433:1433" 
    volumes:
      - /home/$USER/Documentos/sqlserverdb:/home/sql/db 




